targets:
  $default:
    builders:
      freezed:
        options:
          map: false
          when: false
          equal: false
      json_serializable:
        options:
          field_rename: snake